project:
  type: website

website:
  title: "My_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About_Me
      - href: slides/slides.ipynb
        text: Slides

bibliography: references.bib
csl: nature.csl

format:
  html:
    theme: cosmo
    toc: true



